# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  daily_snap_shot:
    class: SnapShotOrchestratorJob
    queue: default
    args: [ 'daily' ]
    schedule: every day
  weekly_snap_shot:
    class: SnapShotOrchestratorJob
    queue: default
    args: [ 'weekly' ]
    schedule: every week
  monthly_snap_shot:
    class: SnapShotOrchestratorJob
    queue: default
    args: [ 'monthly' ]
    schedule: every month